import type { Metadata } from "next";
import "./globals.css";
import '@/styles/index.scss'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "@/components/_common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Header/>
          {children}
          {/* <Footer/> */}
        </AntdRegistry>
      </body>
    </html>
  )
}
